name: pyhat
channels:
  - conda-forge
  - usgs-astrogeology
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - multipledispatch
  - yaml
  - pvl>=1.0
  - plio>=1.3
  - matplotlib
  - pywavelets
  - pip
  - networkx>=2.5
  - pip:
    - pysptools
