name: pyhat
channels:
  - conda-forge
  - usgs-astrogeology
dependencies:
  - python>=3
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - multipledispatch
  - yaml
  - pvl=0.3.0
  - plio
  - matplotlib
  - pywavelets
  - osgeo
  - pip
  - pip:
    - pysptools
